apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: crossplane-instance
spec:
  forProvider:
    region: us-east-1 # For Desired AWS Region
    tags: # For Desired Tags
      Name: crossplane-instance
      Owner: Rohit
    ami: ami-067d1e60475437da2 # For Desired AMI ID
    rootBlockDevice :
      - volumeSize: 50  # For Desired Volume Size
    instanceType: t2.micro # For Desired Instance Type
    vpcSecurityGroupIds:
      - sg-04b1a7ce8f072a440 # For Actual Security Group ID
      - sg-06122688cd0a0913a
    keyName: crossplane-key-pair
  providerConfigRef:
    name: default